apiVersion: v2
name: jaeger
description: Jaeger for sumer project
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: "0.51.5"
